In [1]:
# The autograd package provides automatic gradient calculation.

In [33]:
import torch

In [35]:
input = torch.rand(1,3,64,64)
labels=torch.rand(1,1000)

In [36]:
from torchvision.models import resnet18, ResNet18_Weights
model= resnet18(weights=ResNet18_Weights.DEFAULT)
pred= model(input)

In [37]:
loss = (pred - labels).sum()
loss.backward()
optim= torch.optim.SGD(model.parameters(),lr=.001)
optim.step()

In [38]:
x = torch.rand(5)
y = torch.rand(5)
z = torch.rand((5), requires_grad=True)

In [39]:
a=x+y
a.requires_grad

False

In [40]:
b=x+z
b.requires_grad

True

In [41]:
c=x*z
c.requires_grad

True

In [42]:
a

tensor([0.4485, 1.0185, 0.9539, 1.2003, 0.6007])

In [43]:
b

tensor([0.7289, 0.8793, 1.3517, 1.1732, 0.7945], grad_fn=<AddBackward0>)

In [44]:
c

tensor([0.0104, 0.1895, 0.4559, 0.3406, 0.1485], grad_fn=<MulBackward0>)

In [45]:
c=c.mean()
c

tensor(0.2290, grad_fn=<MeanBackward0>)

In [46]:
z.grad

In [47]:
c.backward()
z.grad #gradient dc/dz

tensor([0.0029, 0.1002, 0.1292, 0.1054, 0.0602])

In [48]:
with torch.no_grad():
    print(z*2)

tensor([1.4287, 0.7565, 1.4117, 1.2922, 0.9873])


In [49]:
#D from scratch

In [50]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True) #parameter we want to optimi

In [51]:
w

tensor(1., requires_grad=True)

In [52]:
#Forward pass to compute loss
pred = w*x    #forward pass
loss = (pred - y)**2 #loss
#Backward pass to compute gradients using chain rule
loss.backward() #backward pass
w.grad # dloss/dw (partial derivatives)

tensor(-2.)

In [53]:
w.grad.zero_() #set gradient to zero

tensor(0.)

In [54]:
x= torch.tensor(3.)
w= torch.tensor(4., requires_grad=True)
b= torch.tensor(1., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(1., requires_grad=True))

In [55]:
y = w * x + b

In [56]:
y

tensor(13., grad_fn=<AddBackward0>)

In [57]:
y.backward()

In [58]:
print(x.grad)

None


In [59]:
print(w.grad)

tensor(3.)


In [60]:
print(b.grad)

tensor(1.)
