In [7]:
import torch
import numpy as np

In [8]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [9]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [10]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [11]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [13]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[9.5112e-01, 9.0003e-02],
        [8.3804e-04, 7.9808e-01]])

In [14]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.3652, 0.1467, 0.9604],
        [0.8282, 0.5038, 0.2975]])

In [15]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
rand_tensor.shape

torch.Size([2, 3])

In [18]:
rand_tensor.dtype

torch.float32

In [19]:
rand_tensor.device

device(type='cpu')

In [20]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [21]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.3652, 1.0000, 0.9604],
        [0.8282, 1.0000, 0.2975]])

In [23]:
rand_tensor[:,0]

tensor([0.3652, 0.8282])

In [22]:
rand_tensor[0]

tensor([0.3652, 1.0000, 0.9604])

In [24]:
rand_tensor[...,-1]

tensor([0.9604, 0.2975])

In [25]:
rand_tensor.sum()

tensor(4.4513)

In [26]:
rand_tensor.sum().item()

4.451266288757324

In [27]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.3652, 1.0000, 0.9604, 0.0000, 0.0000, 0.0000],
        [0.8282, 1.0000, 0.2975, 0.0000, 0.0000, 0.0000]])

In [28]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.3652, 1.0000, 0.9604],
        [0.8282, 1.0000, 0.2975],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [29]:
rand_tensor.mul(ones_tensor)

tensor([[0.3652, 1.0000, 0.9604],
        [0.8282, 1.0000, 0.2975]])

In [30]:
rand_tensor.matmul(rand_tensor.T)

tensor([[2.0557, 1.5881],
        [1.5881, 1.7745]])

In [31]:
rand_tensor.add_(5)

tensor([[5.3652, 6.0000, 5.9604],
        [5.8282, 6.0000, 5.2975]])

In [2]:
torch.empty(1)

tensor([0.])

In [3]:
torch.empty(3)

tensor([0., 0., 0.])

In [4]:
torch.empty(2,3)

tensor([[1.5513e-38, 6.5861e-43, 1.5513e-38],
        [6.5861e-43, 1.5588e-38, 6.5861e-43]])

In [5]:
torch.empty(2,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [6]:
torch.empty(2,2,2,3)

tensor([[[[1.5803e-38, 6.5861e-43, 1.5803e-38],
          [6.5861e-43, 1.5810e-38, 6.5861e-43]],

         [[1.5810e-38, 6.5861e-43, 1.5789e-38],
          [6.5861e-43, 1.5789e-38, 6.5861e-43]]],


        [[[1.5798e-38, 6.5861e-43, 1.5798e-38],
          [6.5861e-43, 1.6807e-38, 6.5861e-43]],

         [[1.6807e-38, 6.5861e-43, 1.6814e-38],
          [6.5861e-43, 1.6814e-38, 6.5861e-43]]]])

In [33]:
m= torch.zeros(2,2,3)
m

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [34]:
torch.zeros(3)

tensor([0., 0., 0.])

In [35]:
torch.ones(3)

tensor([1., 1., 1.])

In [36]:
m.size()

torch.Size([2, 2, 3])

In [38]:
m.dtype

torch.float32

In [39]:
x=torch.zeros(5,3, dtype=torch.float32)

In [40]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [41]:
x.dtype

torch.float32

In [19]:
x=torch.tensor([4,6,7])

In [20]:
x

tensor([4, 6, 7])

In [21]:
x.size()

torch.Size([3])

In [22]:
x=torch.tensor([4,6,7], dtype=torch.float32, requires_grad=True)
x

tensor([4., 6., 7.], requires_grad=True)

In [23]:
y= torch.rand(2,3)

In [24]:
y

tensor([[0.7521, 0.4442, 0.5720],
        [0.1759, 0.5861, 0.1517]])

In [25]:
z= x+y
z

tensor([[4.7521, 6.4442, 7.5720],
        [4.1759, 6.5861, 7.1517]], grad_fn=<AddBackward0>)

In [26]:
torch.add(x,y)

tensor([[4.7521, 6.4442, 7.5720],
        [4.1759, 6.5861, 7.1517]], grad_fn=<AddBackward0>)

In [27]:
y.add_(x)

tensor([[4.7521, 6.4442, 7.5720],
        [4.1759, 6.5861, 7.1517]], grad_fn=<AddBackward0>)

In [28]:
z= x-y
torch.sub(x,y)

tensor([[-0.7521, -0.4442, -0.5720],
        [-0.1759, -0.5861, -0.1517]], grad_fn=<SubBackward0>)

In [29]:
z= x*y
torch.mul(x,y)

tensor([[19.0082, 38.6654, 53.0037],
        [16.7037, 39.5166, 50.0616]], grad_fn=<MulBackward0>)

In [30]:
z= x/y
torch.div(x,y)

tensor([[0.8417, 0.9311, 0.9245],
        [0.9579, 0.9110, 0.9788]], grad_fn=<DivBackward0>)

In [31]:
torch.randn(2,3) # pos-neg value

tensor([[ 0.1856,  1.2338,  1.6420],
        [ 0.9585, -0.2579,  0.5009]])

In [32]:
a=torch.rand(2,3)  # pos value
a

tensor([[0.5031, 0.8586, 0.1295],
        [0.7204, 0.2425, 0.4696]])

In [33]:
a[:,0]

tensor([0.5031, 0.7204])

In [34]:
a[1, :]

tensor([0.7204, 0.2425, 0.4696])

In [35]:
a[1,1]

tensor(0.2425)

In [36]:
a[1,1].item()

0.24250084161758423

In [37]:
b=a.numpy()
b

array([[0.5030785 , 0.8585901 , 0.12948573],
       [0.72040904, 0.24250084, 0.46962047]], dtype=float32)

In [38]:
a=torch.from_numpy(b)
a

tensor([[0.5031, 0.8586, 0.1295],
        [0.7204, 0.2425, 0.4696]])

In [39]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y= torch.ones_like(x, device=device)
  x= x.to(device)
  z=x+y
  z.to("cpu")

In [40]:
x = torch.randn(4,4)
y=x.view(16)
x

tensor([[-0.6083,  0.9469,  0.3348,  0.6343],
        [ 0.6758, -0.3062, -0.4432,  1.4506],
        [ 0.8586,  0.5396, -1.5568, -0.8612],
        [ 1.6909, -0.3126, -1.4379,  0.2257]])

In [41]:
y

tensor([-0.6083,  0.9469,  0.3348,  0.6343,  0.6758, -0.3062, -0.4432,  1.4506,
         0.8586,  0.5396, -1.5568, -0.8612,  1.6909, -0.3126, -1.4379,  0.2257])

In [42]:
z= x.view(-1, 8) # if -1 it pytorch will automatically determine the necessary size
z

tensor([[-0.6083,  0.9469,  0.3348,  0.6343,  0.6758, -0.3062, -0.4432,  1.4506],
        [ 0.8586,  0.5396, -1.5568, -0.8612,  1.6909, -0.3126, -1.4379,  0.2257]])

In [43]:
z.size()

torch.Size([2, 8])

In [44]:
x.shape

torch.Size([4, 4])

In [45]:
x.shape[0]

4

In [46]:
z.shape[0]

2

In [48]:
x

tensor([[-0.6083,  0.9469,  0.3348,  0.6343],
        [ 0.6758, -0.3062, -0.4432,  1.4506],
        [ 0.8586,  0.5396, -1.5568, -0.8612],
        [ 1.6909, -0.3126, -1.4379,  0.2257]])

In [47]:
x.view(x.shape[0],-1)

tensor([[-0.6083,  0.9469,  0.3348,  0.6343],
        [ 0.6758, -0.3062, -0.4432,  1.4506],
        [ 0.8586,  0.5396, -1.5568, -0.8612],
        [ 1.6909, -0.3126, -1.4379,  0.2257]])

In [52]:
m= torch.empty(4,1,2,3)
m

tensor([[[[9.2755e-39, 1.0561e-38, 6.6123e-39],
          [8.4490e-39, 1.0102e-38, 9.0919e-39]]],


        [[[1.0102e-38, 8.9082e-39, 8.4489e-39],
          [9.6429e-39, 8.4490e-39, 9.6429e-39]]],


        [[[9.2755e-39, 1.0286e-38, 9.0919e-39],
          [8.9082e-39, 9.2755e-39, 8.4490e-39]]],


        [[[1.0194e-38, 9.0919e-39, 8.4490e-39],
          [1.1020e-38, 1.0286e-38, 1.0561e-38]]]])